version: "3"

services:
  db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./db_data:/var/lib/mysql:rw
      # - .:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rlatnsxo
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: .
    environment:
      - DBBUG=True
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=survey_api
      - DB_USER=root
      - DB_PASSWORD=rlatnsxo
      - SECRET_KEY=asdf
      - ALGORITHM=HS256
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - db
