FROM python:3.8

MAINTAINER BACKEND MENTORS

ENV PYTHONUNBUFFERED 1

# Set a working directory
WORKDIR /app/

# Install Production Depedencies First
COPY requirements/ /app/requirements/
RUN pip install --no-cache-dir -r requirements/requirements-dev.txt
