version: "3"

services:
  db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./.db:/var/lib/mysql:rw
    env_file:
      - .dockerenv.db.local
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: .
    env_file:
      - .dockerenv.app.local
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - db
