# Generated by Django 3.1.7 on 2021-08-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
