# Generated by Django 3.1.7 on 2021-08-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'survey', 'verbose_name_plural': 'surveys'},
        ),
    ]
