# Generated by Django 3.1.7 on 2021-08-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210803_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={},
        ),
        migrations.AlterModelTable(
            name='survey',
            table='surveys',
        ),
    ]
