# Generated by Django 3.1.7 on 2021-08-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
    ]
