# Generated by Django 3.1.7 on 2021-08-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20210804_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
    ]
